name: KICS Infrastructure as Code Security Scan

on:
  push:
    branches: [main, develop]
    paths:
      - "**.tf"
      - "**/Dockerfile"
      - "**/kubernetes/**"
      - "!**/modules/**" # Исключаем папки с модулями
  pull_request:
    branches: [main]

jobs:
  kics-scan:
    name: KICS Security Scan
    runs-on: ubuntu-latest # Лучшая совместимость с KICS

    steps:
      # Шаг 1: Checkout с подмодулями (если kics как подмодуль)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # Полная история для детекта изменений

      # Шаг 2: Установка KICS (если нет локальной версии)
      - name: Setup KICS
        run: |
          KICS_VERSION=v1.7.2
          wget -q "https://github.com/Checkmarx/kics/releases/download/${KICS_VERSION}/kics_${KICS_VERSION}_linux_x64.tar.gz"
          tar -xzf "kics_${KICS_VERSION}_linux_x64.tar.gz" -C /tmp
          sudo mv "/tmp/kics" /usr/local/bin/
          kics version

      # Шаг 3: Запуск сканирования с продвинутыми параметрами
      - name: Run KICS Scan
        run: |
          kics scan \
            --path . \
            --output-path ./kics-results.sarif \
            --output-name "kics-scan-$(date +%Y%m%d)" \
            --exclude-paths "**/node_modules/**,**/vendor/**,**/.terraform/**" \
            --ignore-on-exit "all" \
            --minimal-ui \
            --verbose

          # Проверка результатов без падения workflow
          if [ -f "./kics-results.sarif" ]; then
            echo "KICS results generated successfully"
            cat ./kics-results.sarif | jq '.runs[0].results | length' | grep -v 0 && exit 1 || exit 0
          fi

      # Шаг 4: Загрузка результатов в GitHub Security
      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./kics-results.sarif
          checkout_path: ${{ github.workspace }}

      # Шаг 5: Уведомление в Slack (опционально)
      - name: Slack Notification
        if: failure()
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "⚠️ KICS found vulnerabilities in ${{ github.repository }}",
              "attachments": [{
                "color": "#ff0000",
                "actions": [{
                  "text": "View Report",
                  "type": "button",
                  "url": "https://github.com/${{ github.repository }}/security/code-scanning"
                }]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
