name: KICS Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  kics-scan:
    name: Run KICS Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies (curl, tar)
        run: sudo apt-get update && sudo apt-get install -y curl tar

      - name: Download and install latest KICS
        run: |
          echo "🔍 Getting latest KICS release..."
          LATEST_URL=$(curl -s https://api.github.com/repos/Checkmarx/kics/releases/latest \
            | grep "browser_download_url" \
            | grep "linux_x64.tar.gz" \
            | cut -d '"' -f 4)

          echo "⬇️ Downloading from $LATEST_URL"
          curl -sSL "$LATEST_URL" -o kics.tar.gz

          mkdir -p kics-bin
          tar -xzf kics.tar.gz -C kics-bin
          sudo mv kics-bin/kics /usr/local/bin/kics
          kics version

      - name: Run KICS scan
        run: |
          mkdir -p kics-results
          kics scan -p . \
            --no-progress \
            --output-path kics-results \
            --output-name result \
            --output-formats json,html \
            --fail-on high

      - name: Upload KICS reports
        uses: actions/upload-artifact@v4
        with:
          name: kics-report
          path: kics-results/
