name: scan with KICS and upload SARIF

on:
  push:
    branches: [main, develop]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v2.1.10
        with:
          path: .
          ignore-on-exit: true
