name: Semgrep Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # Еженедельный запуск (понедельник в 00:00)

jobs:
  semgrep-scan:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Запуск Semgrep (официальное действие)
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          # Опционально: Укажите правила (по умолчанию используются стандартные)
          config: >-
            p/default
            p/security-audit
          # Формат вывода (SARIF для интеграции с GitHub)
          output-format: sarif
          output-file: semgrep-results.sarif

      # Шаг 3: Загрузить результаты в GitHub Security Tab
      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-results.sarif
