name: Semgrep Security Scan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1" # Еженедельный запуск (понедельник в 00:00)

jobs:
  semgrep-scan:
    name: Run Semgrep
    runs-on: windows-latest

    steps:
      # Шаг 1: Получить код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Запуск Semgrep (официальное действие)
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
